version: "3"

services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=sandbox
      - WORDPRESS_DB_PASSWORD=root
    volumes:
      - ./containers/wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/my-plugin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root

  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./containers/mysql:/var/lib/mysql
